export const SIGNAL_TYPES = {
  BUY: 'BUY',
  SELL: 'SELL',
  HOLD: 'HOLD',
};

export const NARRATIVE_TYPES = {
  EXPANDING: 'EXPANDING',
  NEUTRAL: 'NEUTRAL',
  CONTRACTING: 'CONTRACTING',
  CHOPPY: 'CHOPPY',
};

export const MACRO_REGIMES = {
  'RISK-ON': 'RISK-ON',
  'RISK-OFF': 'RISK-OFF',
  TRANSITION: 'TRANSITION',
};

export const MOMENTUM_PHASES = {
  STRONG_UP: 'STRONG_UP',
  MODERATE_UP: 'MODERATE_UP',
  NEUTRAL: 'NEUTRAL',
  MODERATE_DOWN: 'MODERATE_DOWN',
  STRONG_DOWN: 'STRONG_DOWN',
};

export const ETF_FLOW_DIRECTIONS = {
  INFLOW: 'INFLOW',
  OUTFLOW: 'OUTFLOW',
  FLAT: 'FLAT',
};

export const AI_TIERS = {
  WEAK: 'WEAK',
  MODERATE: 'MODERATE',
  STRONG: 'STRONG',
  EXTREME: 'EXTREME',
};
